### ISSUE TITLE
Lyra in Cherenkov branch

### ISSUE THREAD

**Issue by buddhasystem** [BNLNPPS/esi-g4-optical#1]
* Please make sure the lyra code is solid.

* argc>1 on line 82 of opt.cc -- will it trigger a macro execution one this is met, even w/o a valid macro?

**Comment by ggalgoczi** [comment]
Thank you for bringing this up. Now I fixed Lyra CLI arguments. argc>1 is dealt with in commit c8984a0. 

Without arguments GUI starts. With arguments the specified macro runs. For argc>1 the user must define a macro. The reason for this is that for interactive session gui.mac needs to be called.
